"""initial schema

Revision ID: 884712a0e1dd
Revises: 
Create Date: 2026-03-04 17:33:59.725956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884712a0e1dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ACCOUNT',
    sa.Column('AccountID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(), nullable=False),
    sa.Column('PasswordHash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('AccountID'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('BODYPART',
    sa.Column('BodyPartID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Side', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('BodyPartID'),
    sa.UniqueConstraint('Name', 'Side', name='uq_bodypart_name_side'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('PERSON',
    sa.Column('PersonID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FirstName', sa.String(), nullable=True),
    sa.Column('LastName', sa.String(), nullable=True),
    sa.Column('DateOfBirth', sa.Date(), nullable=True),
    sa.Column('AccountID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AccountID'], ['ACCOUNT.AccountID'], ),
    sa.PrimaryKeyConstraint('PersonID'),
    sa.UniqueConstraint('AccountID')
    )
    op.create_table('WORKOUT',
    sa.Column('WorkoutID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('WorkoutName', sa.String(), nullable=False),
    sa.Column('BodyPartID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['BodyPartID'], ['BODYPART.BodyPartID'], ),
    sa.PrimaryKeyConstraint('WorkoutID')
    )
    op.create_table('ATHLETE',
    sa.Column('PersonID', sa.Integer(), nullable=False),
    sa.Column('HoursSpentWorkingOut', sa.Float(), nullable=True),
    sa.Column('SportPlayed', sa.String(), nullable=True),
    sa.Column('Team', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['PersonID'], ['PERSON.PersonID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PersonID')
    )
    op.create_table('COACH',
    sa.Column('PersonID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PersonID'], ['PERSON.PersonID'], ),
    sa.PrimaryKeyConstraint('PersonID')
    )
    op.create_table('ATHLETE_COACH',
    sa.Column('AthletePersonID', sa.Integer(), nullable=False),
    sa.Column('CoachPersonID', sa.Integer(), nullable=False),
    sa.Column('StartDate', sa.Date(), nullable=False),
    sa.Column('EndDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['AthletePersonID'], ['ATHLETE.PersonID'], ),
    sa.ForeignKeyConstraint(['CoachPersonID'], ['COACH.PersonID'], ),
    sa.PrimaryKeyConstraint('AthletePersonID', 'CoachPersonID', 'StartDate')
    )
    op.create_table('ATHLETE_SCORE_HISTORY',
    sa.Column('ScoreID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AthletePersonID', sa.Integer(), nullable=True),
    sa.Column('ScoreDate', sa.Date(), nullable=False),
    sa.Column('InjuryRiskScore', sa.Float(), nullable=True),
    sa.Column('ProgressScore', sa.Float(), nullable=True),
    sa.Column('ModelVersion', sa.String(), nullable=True),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['AthletePersonID'], ['ATHLETE.PersonID'], ),
    sa.PrimaryKeyConstraint('ScoreID')
    )
    op.create_table('COACH_OBSERVATION',
    sa.Column('ObservationID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ObservationDate', sa.Date(), nullable=True),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.Column('CoachPersonID', sa.Integer(), nullable=True),
    sa.Column('AthletePersonID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AthletePersonID'], ['ATHLETE.PersonID'], ),
    sa.ForeignKeyConstraint(['CoachPersonID'], ['COACH.PersonID'], ),
    sa.PrimaryKeyConstraint('ObservationID')
    )
    op.create_table('SORENESS_REPORT',
    sa.Column('ReportID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ReportDate', sa.Date(), nullable=False),
    sa.Column('AthletePersonID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AthletePersonID'], ['ATHLETE.PersonID'], ),
    sa.PrimaryKeyConstraint('ReportID')
    )
    op.create_table('TRAINING_PLAN',
    sa.Column('PlanID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PlanName', sa.String(), nullable=False),
    sa.Column('CoachPersonID', sa.Integer(), nullable=True),
    sa.Column('AthletePersonID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['AthletePersonID'], ['ATHLETE.PersonID'], ),
    sa.ForeignKeyConstraint(['CoachPersonID'], ['COACH.PersonID'], ),
    sa.PrimaryKeyConstraint('PlanID')
    )
    op.create_table('WORKOUT_SESSION',
    sa.Column('SessionID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SessionDate', sa.Date(), nullable=True),
    sa.Column('AthletePersonID', sa.Integer(), nullable=True),
    sa.Column('WorkoutID', sa.Integer(), nullable=True),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['AthletePersonID'], ['ATHLETE.PersonID'], ),
    sa.ForeignKeyConstraint(['WorkoutID'], ['WORKOUT.WorkoutID'], ),
    sa.PrimaryKeyConstraint('SessionID')
    )
    op.create_table('PLAN_WORKOUT',
    sa.Column('PlanID', sa.Integer(), nullable=False),
    sa.Column('WorkoutID', sa.Integer(), nullable=False),
    sa.Column('OrderIndex', sa.Integer(), nullable=True),
    sa.Column('Sets', sa.Integer(), nullable=True),
    sa.Column('Reps', sa.Integer(), nullable=True),
    sa.Column('DurationMinutes', sa.Integer(), nullable=True),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['PlanID'], ['TRAINING_PLAN.PlanID'], ),
    sa.ForeignKeyConstraint(['WorkoutID'], ['WORKOUT.WorkoutID'], ),
    sa.PrimaryKeyConstraint('PlanID', 'WorkoutID')
    )
    op.create_table('SORENESS_ENTRY',
    sa.Column('EntryID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ReportID', sa.Integer(), nullable=True),
    sa.Column('BodyPartID', sa.Integer(), nullable=True),
    sa.Column('SorenessLevel', sa.Integer(), nullable=True),
    sa.CheckConstraint('SorenessLevel BETWEEN 0 AND 10', name='chk_soreness_level'),
    sa.ForeignKeyConstraint(['BodyPartID'], ['BODYPART.BodyPartID'], ),
    sa.ForeignKeyConstraint(['ReportID'], ['SORENESS_REPORT.ReportID'], ),
    sa.PrimaryKeyConstraint('EntryID'),
    sa.UniqueConstraint('ReportID', 'BodyPartID', name='uq_entry_report_bodypart')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SORENESS_ENTRY')
    op.drop_table('PLAN_WORKOUT')
    op.drop_table('WORKOUT_SESSION')
    op.drop_table('TRAINING_PLAN')
    op.drop_table('SORENESS_REPORT')
    op.drop_table('COACH_OBSERVATION')
    op.drop_table('ATHLETE_SCORE_HISTORY')
    op.drop_table('ATHLETE_COACH')
    op.drop_table('COACH')
    op.drop_table('ATHLETE')
    op.drop_table('WORKOUT')
    op.drop_table('PERSON')
    op.drop_table('BODYPART')
    op.drop_table('ACCOUNT')
    # ### end Alembic commands ###
