"use client";

import React, { useRef, useState, Suspense } from 'react';
import Link from 'next/link';
import { Upload, ArrowLeft, Activity, CheckCircle, Box, SlidersHorizontal, Ruler, Dumbbell, Droplets } from 'lucide-react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, ContactShadows, useGLTF, Environment } from '@react-three/drei';
import * as THREE from 'three';
import { Object3D, Mesh } from 'three';

interface AnnyResponse {
    status: string;
    mesh_url: string;
}

// --- NEW: THE REAL 3D MESH LOADER ---
function RealHumanMesh({ modelUrl }: { modelUrl: string }) {
    const groupRef = useRef<THREE.Object3D>(null);

    // This hooks into your public folder and loads the file generated by Python
    const { scene } = useGLTF(modelUrl);

    // Slowly rotate the actual mesh
    useFrame((state, delta) => {
        if (groupRef.current) {
            groupRef.current.rotation.y += delta * 0.5;
        }
    });

    // Apply a brighter "Hologram" material
    scene.traverse((child: THREE.Object3D) => {
        // Check if the object is a Mesh to access material properties
        if ((child as THREE.Mesh).isMesh) {
            const mesh = child as THREE.Mesh;
            const material = mesh.material as THREE.MeshStandardMaterial;

            if (material) {
                material.color.set("#22d3ee");
                material.transparent = true;
                material.opacity = 0.95;
                material.roughness = 0.3;
                material.metalness = 0.7;
            }
        }
    });

    return (
        <group ref={groupRef} position={[0, 0, 0]} scale={1.7}>
            <primitive object={scene} />
        </group>
    );
}

export default function AnnyModelTest() {
    const [isProcessing, setIsProcessing] = useState(false);
    const [resultData, setResultData] = useState<AnnyResponse | null>(null);

    const [height, setHeight] = useState(175);
    const [bodyFat, setBodyFat] = useState(15);
    const [muscleMass, setMuscleMass] = useState(8.0);

    const generateParametricMesh = async () => {
        setIsProcessing(true);
        setResultData(null);

        try {
            // Hit the real Python Backend with the Slider Data
            const response = await fetch('http://localhost:8000/api/generate-mesh', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    height_cm: height,
                    estimated_bf_percent: bodyFat,
                    muscle_mass_index: muscleMass
                })
            });

            if (!response.ok) throw new Error("Backend failed");

            const data = await response.json();
            setResultData(data);

        } catch (error) {
            console.error("API Error:", error);
            alert("Make sure Uvicorn is running!");
        } finally {
            setIsProcessing(false);
        }
    };

    return (
        <main className="min-h-screen bg-slate-950 text-white flex flex-col items-center p-6">
            <div className="w-full max-w-5xl flex justify-between items-center mb-8 pt-4">
                <Link href="/login" className="text-slate-500 hover:text-white flex items-center gap-2 transition-colors">
                    <ArrowLeft size={20} />
                    <span>Exit Sandbox</span>
                </Link>
                <div className="font-mono text-cyan-500 border border-cyan-500 px-3 py-1 rounded text-sm flex items-center gap-2">
                    <Activity size={16} />
                    Anny Parametric Sandbox
                </div>
            </div>

            <div className="w-full max-w-5xl grid grid-cols-1 md:grid-cols-2 gap-8">

                {/* Sliders */}
                <div className="bg-slate-900 border border-slate-800 rounded-2xl p-8 shadow-2xl flex flex-col h-[600px]">
                    <div className="flex items-center gap-3 mb-8 pb-4 border-b border-slate-800">
                        <div className="p-3 bg-cyan-500/10 rounded-lg">
                            <SlidersHorizontal className="text-cyan-400 w-6 h-6" />
                        </div>
                        <div>
                            <h2 className="text-xl font-bold">Semantic Controls</h2>
                            <p className="text-slate-400 text-sm">Adjust biometrics to generate mesh</p>
                        </div>
                    </div>

                    <div className="flex-1 space-y-8">
                        <div>
                            <div className="flex justify-between items-end mb-2">
                                <label className="text-sm font-bold text-slate-300 flex items-center gap-2"><Ruler size={16} className="text-cyan-500" /> Height (cm)</label>
                                <span className="font-mono text-xl text-cyan-400">{height}</span>
                            </div>
                            <input type="range" min="140" max="220" value={height} onChange={(e) => setHeight(Number(e.target.value))} className="w-full accent-cyan-500 cursor-pointer" />
                        </div>

                        <div>
                            <div className="flex justify-between items-end mb-2">
                                <label className="text-sm font-bold text-slate-300 flex items-center gap-2"><Droplets size={16} className="text-cyan-500" /> Body Fat (%)</label>
                                <span className="font-mono text-xl text-cyan-400">{bodyFat}</span>
                            </div>
                            <input type="range" min="3" max="40" value={bodyFat} onChange={(e) => setBodyFat(Number(e.target.value))} className="w-full accent-cyan-500 cursor-pointer" />
                        </div>

                        <div>
                            <div className="flex justify-between items-end mb-2">
                                <label className="text-sm font-bold text-slate-300 flex items-center gap-2"><Dumbbell size={16} className="text-cyan-500" /> Muscle Mass Index</label>
                                <span className="font-mono text-xl text-cyan-400">{muscleMass.toFixed(1)}</span>
                            </div>
                            <input type="range" min="5.0" max="15.0" step="0.1" value={muscleMass} onChange={(e) => setMuscleMass(Number(e.target.value))} className="w-full accent-cyan-500 cursor-pointer" />
                        </div>
                    </div>

                    <button onClick={generateParametricMesh} disabled={isProcessing} className="w-full py-4 mt-6 bg-cyan-500 text-black font-bold rounded-lg hover:bg-cyan-400 transition-colors disabled:opacity-50 flex justify-center items-center gap-2">
                        {isProcessing ? <Activity className="animate-pulse" /> : <Upload size={20} />}
                        {isProcessing ? "Generating Digital Twin..." : "Generate Digital Twin"}
                    </button>
                </div>

                {/* 3D Viewer */}
                <div className={`bg-slate-900 border border-slate-800 rounded-2xl flex flex-col shadow-2xl transition-all duration-700 h-[600px] overflow-hidden ${resultData ? 'opacity-100 translate-x-0' : 'opacity-20 translate-x-4 pointer-events-none'}`}>
                    <div className="h-[60%] relative bg-slate-950 border-b border-slate-800 cursor-grab active:cursor-grabbing">
                        {resultData && (
                            <Canvas camera={{ position: [0, 0, 4.5], fov: 50 }}>
                                {/* 1. Base brightness so nothing is pitch black */}
                                <ambientLight intensity={0.8} />

                                {/* 2. Main "Key" light from front-right */}
                                <directionalLight position={[5, 5, 5]} intensity={2.5} />

                                {/* 3. "Fill" light from the left to soften shadows */}
                                <directionalLight position={[-5, 5, 2]} intensity={1} />

                                {/* 4. Real-world reflections (makes the metal look real) */}
                                <Environment preset="city" />

                                <Suspense fallback={null}>
                                    <RealHumanMesh modelUrl={resultData.mesh_url || "/generated_twin.glb"} />
                                </Suspense>

                                <OrbitControls enableZoom={true} enablePan={false} minDistance={3} maxDistance={10} />
                                <ContactShadows position={[0, -1.85, 0]} opacity={0.5} scale={10} blur={2.5} far={4} color="#06b6d4" />
                            </Canvas>
                        )}

                        <div className="absolute top-4 left-4 flex flex-col gap-2 pointer-events-none">
                            <div className="bg-slate-900/80 backdrop-blur border border-slate-700 px-3 py-1.5 rounded flex items-center gap-2">
                                <Box className="w-4 h-4 text-cyan-500" />
                                <span className="text-xs font-bold text-white uppercase tracking-wider">Parametric Output</span>
                            </div>
                        </div>
                    </div>

                    <div className="h-[40%] p-6 bg-slate-900 overflow-y-auto">
                        {resultData && (
                            <div className="space-y-4 animate-in fade-in slide-in-from-bottom-4">
                                <div className="flex items-center gap-3 text-green-400 mb-4">
                                    <CheckCircle size={20} />
                                    <div className="text-sm font-bold">Mesh Successfully Loaded from Python</div>
                                </div>
                                <p className="text-slate-400 text-sm">
                                    The model above was loaded from <code className="text-cyan-400">{resultData.mesh_url}</code>.
                                </p>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </main>
    );
}

// Ensure Drei preloads the file so it snaps in instantly
useGLTF.preload('/generated_twin.glb');

/* ================================================================================
  PRESERVED CAMERA CODE 
  (Uncomment and integrate this if you want to switch back to the 2D capture flow later)
================================================================================

  const videoRef = useRef<HTMLVideoElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [step, setStep] = useState<'intro' | 'camera' | 'review'>('intro');
  const [imageSrc, setImageSrc] = useState<string | null>(null);
  const [stream, setStream] = useState<MediaStream | null>(null);
  const [countdown, setCountdown] = useState<number | null>(null);

  const startCamera = async () => { ... }
  const stopCamera = () => { ... }
  const handleReadyAndStart = async () => { ... }
  const startTimer = () => { ... }
  const executeCapture = () => { ... }
  const retakePhoto = () => { ... }
*/